default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
        args: ["--line-length", "240"]
  - repo: local
    hooks:
      - id: mypy
        name: Type checking all files
        entry: uv run mypy src
        files: 'src'
        pass_filenames: false
        types_or: [ python, pyi ]
        stages: 
          - pre-commit
          - manual
          - pre-push
        language: system
